CREATE TABLE `research_studies` (
	`id` int AUTO_INCREMENT NOT NULL,
	`slug` varchar(255) NOT NULL,
	`original_title` text NOT NULL,
	`doi` varchar(255),
	`pubmed_id` varchar(50),
	`source_url` varchar(500) NOT NULL,
	`journal` varchar(255) NOT NULL,
	`university` varchar(255),
	`authors` text,
	`publish_date` date NOT NULL,
	`study_type` varchar(100) NOT NULL,
	`evidence_level` varchar(50) NOT NULL,
	`participant_count` int,
	`is_preliminary` boolean NOT NULL DEFAULT false,
	`is_human_study` boolean NOT NULL DEFAULT true,
	`primary_topic` varchar(100) NOT NULL,
	`topics` json NOT NULL,
	`title_ar` text NOT NULL,
	`title_en` text NOT NULL,
	`summary_30s_ar` text NOT NULL,
	`summary_30s_en` text NOT NULL,
	`summary_1min_ar` text NOT NULL,
	`summary_1min_en` text NOT NULL,
	`summary_3min_ar` text NOT NULL,
	`summary_3min_en` text NOT NULL,
	`full_analysis_ar` text NOT NULL,
	`full_analysis_en` text NOT NULL,
	`health_implications_ar` text NOT NULL,
	`health_implications_en` text NOT NULL,
	`key_findings` json NOT NULL,
	`strengths_weaknesses` json,
	`feel_great_connection` text,
	`feel_great_connection_ar` text,
	`meta_title_en` varchar(255),
	`meta_title_ar` varchar(255),
	`meta_description_en` text,
	`meta_description_ar` text,
	`hero_image_url` varchar(500),
	`view_count` int NOT NULL DEFAULT 0,
	`impact_score` int NOT NULL DEFAULT 0,
	`is_published` boolean NOT NULL DEFAULT true,
	`created_at` timestamp NOT NULL DEFAULT (now()),
	`updated_at` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `research_studies_id` PRIMARY KEY(`id`),
	CONSTRAINT `research_studies_slug_unique` UNIQUE(`slug`)
);
--> statement-breakpoint
CREATE INDEX `idx_research_topic` ON `research_studies` (`primary_topic`);--> statement-breakpoint
CREATE INDEX `idx_research_published` ON `research_studies` (`is_published`);--> statement-breakpoint
CREATE INDEX `idx_research_date` ON `research_studies` (`publish_date`);--> statement-breakpoint
CREATE INDEX `idx_research_evidence` ON `research_studies` (`evidence_level`);