/**
 * FeelGreat.us.com - Bulk Content Seeder
 * Run this to seed all 55 articles and 52 research studies
 *
 * Usage: POST /api/seed-all-content
 * Requires: Admin authentication
 */

import type { Request, Response } from "express";
import { createBlogArticle, createResearchStudy, getArticlesCount, getResearchCount } from "../db";

// ============================================================
// 55 ARTICLES DATA
// ============================================================
const ARTICLES = [
  // INSULIN RESISTANCE (10)
  {
    slug: "understanding-insulin-resistance-silent-epidemic",
    titleAr: "فهم مقاومة الأنسولين: الوباء الصامت",
    titleEn: "Understanding Insulin Resistance: The Silent Epidemic",
    excerptAr: "اكتشف ما هو مقاومة الأنسولين ولماذا يعتبر وباءً صامتاً يهدد الملايين حول العالم.",
    excerptEn: "Discover what insulin resistance is and why it's considered a silent epidemic threatening millions.",
    contentAr: `<h2>ما هو مقاومة الأنسولين؟</h2><p>مقاومة الأنسولين هي حالة طبية تحدث عندما لا تستجيب خلايا الجسم لهرمون الأنسولين بشكل صحيح.</p><h2>لماذا يُسمى بالوباء الصامت؟</h2><p>الخطير في مقاومة الأنسولين أنها غالباً لا تظهر أي أعراض واضحة في مراحلها المبكرة.</p><h2>العلامات التحذيرية</h2><ul><li>زيادة الوزن خاصة حول البطن</li><li>صعوبة فقدان الوزن</li><li>التعب المستمر</li><li>الرغبة الشديدة في السكريات</li></ul><h2>ماذا تقول الدراسات العلمية؟</h2><p>أظهرت دراسة نُشرت في مجلة The Lancet أن أكثر من 88% من البالغين يعانون من درجة ما من مقاومة الأنسولين دون علمهم.</p>`,
    contentEn: `<h2>What is Insulin Resistance?</h2><p>Insulin resistance is a medical condition where the body's cells don't respond properly to insulin.</p><h2>Why is it Called the Silent Epidemic?</h2><p>The danger of insulin resistance lies in its often asymptomatic nature in early stages.</p><h2>Warning Signs</h2><ul><li>Weight gain, especially around the abdomen</li><li>Difficulty losing weight</li><li>Constant fatigue</li><li>Strong cravings for sweets</li></ul><h2>What Do Scientific Studies Say?</h2><p>A study published in The Lancet showed that more than 88% of adults have some degree of insulin resistance without knowing it.</p>`,
    category: "insulin-resistance",
    tags: ["insulin resistance", "metabolic health", "blood sugar", "pre-diabetes"],
    keywords: "insulin resistance, metabolic health, blood sugar, pre-diabetes",
    metaTitleAr: "مقاومة الأنسولين: الوباء الصامت",
    metaTitleEn: "Understanding Insulin Resistance: The Silent Epidemic",
    metaDescriptionAr: "دليل شامل عن مقاومة الأنسولين.",
    metaDescriptionEn: "Comprehensive guide to insulin resistance.",
    pillarId: "insulin-resistance",
    clusterId: "insulin-resistance",
    targetKeyword: "insulin resistance",
    wordCount: 1500,
    readTimeMinutes: 8
  },
  {
    slug: "reverse-insulin-resistance-90-days",
    titleAr: "كيف تعكس مقاومة الأنسولين في 90 يوماً",
    titleEn: "How to Reverse Insulin Resistance in 90 Days",
    excerptAr: "برنامج علمي مدعوم بالأبحاث الطبية لإعادة حساسية الجسم للأنسولين.",
    excerptEn: "A science-backed program to restore your body's insulin sensitivity.",
    contentAr: `<h2>فهم الأساس العلمي</h2><p>مقاومة الأنسولين قابلة للعكس تماماً إذا تم التعامل معها بالطريقة الصحيحة.</p><h2>الخطوة الأولى: تحسين النظام الغذائي</h2><p>ابدأ بتقليل الكربوهيدرات المكررة وزيادة الألياف القابلة للذوبان.</p>`,
    contentEn: `<h2>Understanding the Science</h2><p>Insulin resistance is completely reversible if addressed correctly.</p><h2>Step One: Improve Your Diet</h2><p>Start by reducing refined carbohydrates and increasing soluble fiber.</p>`,
    category: "insulin-resistance",
    tags: ["reverse insulin resistance", "insulin resistance treatment"],
    keywords: "reverse insulin resistance, insulin resistance treatment",
    metaTitleAr: "كيف تعكس مقاومة الأنسولين في 90 يوماً",
    metaTitleEn: "How to Reverse Insulin Resistance in 90 Days",
    metaDescriptionAr: "برنامج علمي لإعادة حساسية الأنسولين.",
    metaDescriptionEn: "A science-backed program to restore insulin sensitivity.",
    pillarId: "insulin-resistance",
    clusterId: "insulin-resistance",
    targetKeyword: "reverse insulin resistance",
    wordCount: 1400,
    readTimeMinutes: 7
  },
  {
    slug: "insulin-resistance-weight-gain-connection",
    titleAr: "العلاقة بين مقاومة الأنسولين وزيادة الوزن",
    titleEn: "The Connection Between Insulin Resistance and Weight Gain",
    excerptAr: "اكتشف كيف ترتبط مقاومة الأنسولين بزيادة الوزن العنيدة.",
    excerptEn: "Discover how insulin resistance is linked to stubborn weight gain.",
    contentAr: `<h2>كيف يسبب الأنسولين زيادة الوزن؟</h2><p>عندما تكون مقاومة للأنسولين، يرتفع مستوى الأنسولين في الدم مما يعزز تخزين الدهون.</p>`,
    contentEn: `<h2>How Does Insulin Cause Weight Gain?</h2><p>When you're insulin resistant, insulin levels rise, promoting fat storage.</p>`,
    category: "insulin-resistance",
    tags: ["insulin resistance weight loss", "stubborn belly fat"],
    keywords: "insulin resistance weight loss, stubborn belly fat",
    metaTitleAr: "العلاقة بين مقاومة الأنسولين وزيادة الوزن",
    metaTitleEn: "The Connection Between Insulin Resistance and Weight Gain",
    pillarId: "insulin-resistance",
    clusterId: "insulin-resistance",
    targetKeyword: "insulin resistance weight gain",
    wordCount: 1300,
    readTimeMinutes: 6
  },
  {
    slug: "best-diet-insulin-resistance-complete-guide",
    titleAr: "أفضل نظام غذائي لمقاومة الأنسولين",
    titleEn: "Best Diet for Insulin Resistance: A Complete Guide",
    excerptAr: "دليل علمي شامل لأفضل الأنظمة الغذائية المفيدة لمقاومة الأنسولين.",
    excerptEn: "A comprehensive scientific guide to the best diets for insulin resistance.",
    contentAr: `<h2>مبادئ التغذية لمقاومة الأنسولين</h2><p>التركيز على الأطعمة منخفضة المؤشر الجلايسيمي مع نسبة عالية من الألياف هو المفتاح.</p>`,
    contentEn: `<h2>Nutrition Principles for Insulin Resistance</h2><p>Focusing on low-glycemic index foods with high fiber content is key.</p>`,
    category: "insulin-resistance",
    tags: ["insulin resistance diet", "low glycemic diet"],
    keywords: "insulin resistance diet, low glycemic diet",
    metaTitleAr: "أفضل نظام غذائي لمقاومة الأنسولين",
    metaTitleEn: "Best Diet for Insulin Resistance: A Complete Guide",
    pillarId: "insulin-resistance",
    clusterId: "insulin-resistance",
    targetKeyword: "insulin resistance diet",
    wordCount: 1600,
    readTimeMinutes: 8
  },
  {
    slug: "signs-symptoms-insulin-resistance",
    titleAr: "علامات وأعراض مقاومة الأنسولين",
    titleEn: "Signs and Symptoms of Insulin Resistance You Should Know",
    excerptAr: "تعرف على العلامات التحذيرية لمقاومة الأنسولين قبل فوات الأوان.",
    excerptEn: "Learn the warning signs of insulin resistance before it's too late.",
    contentAr: `<h2>أعراض رئيسية</h2><p>التفاح الأسود حول الرقبة، الرغبة الشديدة في النوم بعد الأكل، وصعوبة التركيز.</p>`,
    contentEn: `<h2>Key Symptoms</h2><p>Darkened skin around the neck, desire to sleep after eating, difficulty concentrating.</p>`,
    category: "insulin-resistance",
    tags: ["insulin resistance symptoms", "warning signs"],
    keywords: "insulin resistance symptoms, warning signs",
    metaTitleAr: "علامات مقاومة الأنسولين",
    metaTitleEn: "Signs and Symptoms of Insulin Resistance",
    pillarId: "insulin-resistance",
    clusterId: "insulin-resistance",
    targetKeyword: "insulin resistance symptoms",
    wordCount: 1200,
    readTimeMinutes: 6
  },
  {
    slug: "insulin-resistance-womens-health",
    titleAr: "كيف تؤثر مقاومة الأنسولين على صحة المرأة",
    titleEn: "How Insulin Resistance Affects Women's Health",
    excerptAr: "تأثير خاص على النساء: متلازمة تكيس المبايض والحمل.",
    excerptEn: "Special impact on women: PCOS and pregnancy.",
    contentAr: `<h2>متلازمة تكيس المبايض (PCOS)</h2><p>ما بين 50-70% من النساء المصابات بتكيس المبايض يعانين من مقاومة الأنسولين.</p>`,
    contentEn: `<h2>Polycystic Ovary Syndrome (PCOS)</h2><p>Between 50-70% of women with PCOS have insulin resistance.</p>`,
    category: "insulin-resistance",
    tags: ["PCOS", "insulin resistance women"],
    keywords: "PCOS, insulin resistance women",
    metaTitleAr: "مقاومة الأنسولين وصحة المرأة",
    metaTitleEn: "How Insulin Resistance Affects Women's Health",
    pillarId: "insulin-resistance",
    clusterId: "insulin-resistance",
    targetKeyword: "insulin resistance women",
    wordCount: 1400,
    readTimeMinutes: 7
  },
  {
    slug: "exercise-managing-insulin-resistance",
    titleAr: "دور التمارين في إدارة مقاومة الأنسولين",
    titleEn: "The Role of Exercise in Managing Insulin Resistance",
    excerptAr: "كيف يمكن للتمارين أن تحسن حساسية الأنسولين.",
    excerptEn: "How exercise can improve insulin sensitivity.",
    contentAr: `<h2>نوع التمرين يهم</h2><p>تمارين المقاومة والكارديو معاً لهما تأثير مضاعف على حساسية الأنسولين.</p>`,
    contentEn: `<h2>Type of Exercise Matters</h2><p>Resistance and cardio exercises together have a synergistic effect on insulin sensitivity.</p>`,
    category: "insulin-resistance",
    tags: ["insulin resistance exercise", "workout"],
    keywords: "insulin resistance exercise, workout",
    metaTitleAr: "التمارين ومقاومة الأنسولين",
    metaTitleEn: "The Role of Exercise in Managing Insulin Resistance",
    pillarId: "insulin-resistance",
    clusterId: "insulin-resistance",
    targetKeyword: "insulin resistance exercise",
    wordCount: 1100,
    readTimeMinutes: 5
  },
  {
    slug: "hba1c-test-meaning-your-health",
    titleAr: "فهم فحص HbA1c: ماذا يعني لصحتك",
    titleEn: "Understanding the HbA1c Test: What It Means for Your Health",
    excerptAr: "كل ما تحتاج معرفته عن فحص HbA1c.",
    excerptEn: "Everything you need to know about the HbA1c test.",
    contentAr: `<h2>ما هو HbA1c؟</h2><p>فحص HbA1c يقيس متوسط مستوى السكر في الدم خلال آخر 2-3 أشهر.</p>`,
    contentEn: `<h2>What is HbA1c?</h2><p>The HbA1c test measures average blood sugar levels over the last 2-3 months.</p>`,
    category: "insulin-resistance",
    tags: ["HbA1c", "blood sugar test"],
    keywords: "HbA1c, blood sugar test",
    metaTitleAr: "فهم فحص HbA1c",
    metaTitleEn: "Understanding the HbA1c Test",
    pillarId: "insulin-resistance",
    clusterId: "insulin-resistance",
    targetKeyword: "HbA1c test",
    wordCount: 1300,
    readTimeMinutes: 6
  },
  {
    slug: "sleep-insulin-sensitivity-connection",
    titleAr: "كيف يؤثر النوم على حساسية الأنسولين",
    titleEn: "How Sleep Affects Insulin Sensitivity",
    excerptAr: "العلاقة المذهلة بين جودة النوم والصحة الأيضية.",
    excerptEn: "The amazing connection between sleep quality and metabolic health.",
    contentAr: `<h2>النوم والاستقلاب</h2><p>ساعة واحدة فقط من قلة النوم يمكن أن تقلل حساسية الأنسولين بنسبة 30%.</p>`,
    contentEn: `<h2>Sleep and Metabolism</h2><p>Just one hour of sleep deprivation can reduce insulin sensitivity by 30%.</p>`,
    category: "insulin-resistance",
    tags: ["sleep", "insulin resistance"],
    keywords: "sleep, insulin resistance",
    metaTitleAr: "النوم وحساسية الأنسولين",
    metaTitleEn: "How Sleep Affects Insulin Sensitivity",
    pillarId: "insulin-resistance",
    clusterId: "insulin-resistance",
    targetKeyword: "sleep insulin sensitivity",
    wordCount: 1200,
    readTimeMinutes: 6
  },
  {
    slug: "supplements-insulin-resistance-management",
    titleAr: "المكملات التي تساعد في إدارة مقاومة الأنسولين",
    titleEn: "Supplements That Help Manage Insulin Resistance",
    excerptAr: "المكملات الغذائية المدعومة بالأدلة العلمية.",
    excerptEn: "Nutritional supplements backed by scientific evidence.",
    contentAr: `<h2>مكملات أساسية</h2><p>البربرين، الكروميوم، والمغنيسيوم من أكثر المكملات المدعومة بالأدلة العلمية.</p>`,
    contentEn: `<h2>Essential Supplements</h2><p>Berberine, chromium, and magnesium are among the most evidence-supported supplements.</p>`,
    category: "insulin-resistance",
    tags: ["insulin resistance supplements", "berberine"],
    keywords: "insulin resistance supplements, berberine",
    metaTitleAr: "مكملات مقاومة الأنسولين",
    metaTitleEn: "Supplements for Insulin Resistance",
    pillarId: "insulin-resistance",
    clusterId: "insulin-resistance",
    targetKeyword: "insulin resistance supplements",
    wordCount: 1400,
    readTimeMinutes: 7
  },
  // SUSTAINABLE HEALTH (8)
  {
    slug: "sustainable-health-why-matters",
    titleAr: "ما هي الصحة المستدامة ولماذا تهم؟",
    titleEn: "What is Sustainable Health and Why Does It Matter?",
    excerptAr: "مفهوم جديد للصحة يدوم مدى الحياة.",
    excerptEn: "A new concept of health that lasts a lifetime.",
    contentAr: `<h2>تعريف الصحة المستدامة</h2><p>الصحة المستدامة ليست مجرد حمية مؤقتة أو تمرين موسمي.</p>`,
    contentEn: `<h2>Defining Sustainable Health</h2><p>Sustainable health isn't just a temporary diet or seasonal exercise.</p>`,
    category: "sustainable-health",
    tags: ["sustainable health", "healthy lifestyle"],
    keywords: "sustainable health, healthy lifestyle",
    metaTitleAr: "الصحة المستدامة",
    metaTitleEn: "What is Sustainable Health",
    pillarId: "sustainable-health",
    clusterId: "sustainable-health",
    targetKeyword: "sustainable health",
    wordCount: 1300,
    readTimeMinutes: 6
  },
  {
    slug: "feras-alayed-method-science-backed",
    titleAr: "طريقة فراس العايد: نهج علمي مدعوم",
    titleEn: "The Feras Alayed Method: A Science-Backed Approach to Health",
    excerptAr: "منهجية متكاملة تجمع بين العلم والتطبيق العملي.",
    excerptEn: "An integrated methodology combining science and practical application.",
    contentAr: `<h2>أسس المنهجية</h2><p>تعتمد طريقة فراس العايد على الجمع بين أحدث الأبحاث العلمية والخبرة السريرية.</p>`,
    contentEn: `<h2>Methodology Foundations</h2><p>The Feras Alayed Method relies on combining the latest scientific research with clinical experience.</p>`,
    category: "sustainable-health",
    tags: ["Feras Alayed Method", "health transformation"],
    keywords: "Feras Alayed Method, health transformation",
    metaTitleAr: "طريقة فراس العايد",
    metaTitleEn: "The Feras Alayed Method",
    pillarId: "sustainable-health",
    clusterId: "sustainable-health",
    targetKeyword: "feras alayed method",
    wordCount: 1200,
    readTimeMinutes: 6
  },
  {
    slug: "build-lasting-healthy-habits",
    titleAr: "كيف تبني عادات صحية تدوم",
    titleEn: "How to Build Lasting Healthy Habits",
    excerptAr: "علم بناء العادات التي تغير حياتك.",
    excerptEn: "The science of building habits that change your life.",
    contentAr: `<h2>إعادة بناء العادات</h2><p>العادات تدوم عندما تتوافق مع هويتك الشخصية.</p>`,
    contentEn: `<h2>Rebuilding Habits</h2><p>Habits last when they align with your personal identity.</p>`,
    category: "sustainable-health",
    tags: ["healthy habits", "habit formation"],
    keywords: "healthy habits, habit formation",
    metaTitleAr: "بناء العادات الصحية",
    metaTitleEn: "How to Build Lasting Healthy Habits",
    pillarId: "sustainable-health",
    clusterId: "sustainable-health",
    targetKeyword: "build healthy habits",
    wordCount: 1400,
    readTimeMinutes: 7
  },
  {
    slug: "metabolic-health-modern-life",
    titleAr: "أهمية الصحة الأيضية في الحياة العصرية",
    titleEn: "The Importance of Metabolic Health in Modern Life",
    excerptAr: "صحة التمثيل الغذائي هي أساس كل شيء.",
    excerptEn: "Metabolic health is the foundation of everything.",
    contentAr: `<h2>ما هو التمثيل الغذائي؟</h2><p>الصحة الأيضية تؤثر على كل شيء من طاقتك اليومية إلى خطر الأمراض المزمنة.</p>`,
    contentEn: `<h2>What is Metabolism?</h2><p>Metabolic health affects everything from your daily energy to the risk of chronic diseases.</p>`,
    category: "sustainable-health",
    tags: ["metabolic health", "modern lifestyle"],
    keywords: "metabolic health, modern lifestyle",
    metaTitleAr: "الصحة الأيضية",
    metaTitleEn: "Metabolic Health in Modern Life",
    pillarId: "sustainable-health",
    clusterId: "sustainable-health",
    targetKeyword: "metabolic health",
    wordCount: 1300,
    readTimeMinutes: 6
  },
  {
    slug: "90-day-health-transformation-process",
    titleAr: "فهم عملية التحول الصحي في 90 يوماً",
    titleEn: "Understanding the 90-Day Health Transformation Process",
    excerptAr: "90 يوماً يمكن أن تغير حياتك الصحية.",
    excerptEn: "90 days can change your health life.",
    contentAr: `<h2>لماذا 90 يوماً؟</h2><p>العلم يقول أن 90 يوماً كافية لتغيير نمط حياة كامل.</p>`,
    contentEn: `<h2>Why 90 Days?</h2><p>Science says 90 days is enough to change an entire lifestyle.</p>`,
    category: "sustainable-health",
    tags: ["90 day challenge", "health transformation"],
    keywords: "90 day challenge, health transformation",
    metaTitleAr: "التحول الصحي في 90 يوماً",
    metaTitleEn: "90-Day Health Transformation",
    pillarId: "sustainable-health",
    clusterId: "sustainable-health",
    targetKeyword: "90 day health transformation",
    wordCount: 1200,
    readTimeMinutes: 6
  },
  {
    slug: "personalized-health-plan-guide",
    titleAr: "كيف تنشئ خطة صحية شخصية",
    titleEn: "How to Create Your Personalized Health Plan",
    excerptAr: "خطة مصممة خصيصاً لطبيعة جسمك وأهدافك.",
    excerptEn: "A plan designed specifically for your body type and goals.",
    contentAr: `<h2>التقييم الأولي</h2><p>كل جسم فريد. خطتك الصحية يجب أن تعكس خصوصياتك.</p>`,
    contentEn: `<h2>Initial Assessment</h2><p>Every body is unique. Your health plan should reflect your uniqueness.</p>`,
    category: "sustainable-health",
    tags: ["personalized health", "wellness plan"],
    keywords: "personalized health, wellness plan",
    metaTitleAr: "خطة صحية شخصية",
    metaTitleEn: "Personalized Health Plan",
    pillarId: "sustainable-health",
    clusterId: "sustainable-health",
    targetKeyword: "personalized health plan",
    wordCount: 1400,
    readTimeMinutes: 7
  },
  {
    slug: "nutrition-sustainable-weight-management",
    titleAr: "دور التغذية في إدارة الوزن المستدامة",
    titleEn: "The Role of Nutrition in Sustainable Weight Management",
    excerptAr: "التغذية ليست حرماناً، بل هي طاقة.",
    excerptEn: "Nutrition is not deprivation, it's energy.",
    contentAr: `<h2>إعادة تعريف التغذية</h2><p>النظام الغذائي الناجح يدور حول التغذية وليس الحرمان.</p>`,
    contentEn: `<h2>Redefining Nutrition</h2><p>Successful dieting is about nutrition, not deprivation.</p>`,
    category: "sustainable-health",
    tags: ["sustainable weight loss", "healthy eating"],
    keywords: "sustainable weight loss, healthy eating",
    metaTitleAr: "التغذية وإدارة الوزن",
    metaTitleEn: "Nutrition and Weight Management",
    pillarId: "sustainable-health",
    clusterId: "sustainable-health",
    targetKeyword: "sustainable weight loss",
    wordCount: 1300,
    readTimeMinutes: 6
  },
  {
    slug: "why-diets-fail-what-works",
    titleAr: "لماذا تفشل معظم الحميات وماذا يعمل فعلاً",
    titleEn: "Why Most Diets Fail and What Actually Works",
    excerptAr: "سر النجاة طويل الأمد في رحلة إنقاص الوزن.",
    excerptEn: "The secret to long-term success in weight loss journey.",
    contentAr: `<h2>لماذا تفشل الحميات؟</h2><p>معظم الحميات تفشل لأنها تستهدف الأعراض وليس الأسباب.</p>`,
    contentEn: `<h2>Why Diets Fail</h2><p>Most diets fail because they target symptoms, not causes.</p>`,
    category: "sustainable-health",
    tags: ["diet failure", "weight management"],
    keywords: "diet failure, weight management",
    metaTitleAr: "لماذا تفشل الحميات؟",
    metaTitleEn: "Why Most Diets Fail",
    pillarId: "sustainable-health",
    clusterId: "sustainable-health",
    targetKeyword: "why diets fail",
    wordCount: 1400,
    readTimeMinutes: 7
  },
  // WEIGHT MANAGEMENT (8)
  {
    slug: "science-behind-sustainable-weight-loss",
    titleAr: "العلم وراء إنقاص الوزن المستدام",
    titleEn: "The Science Behind Sustainable Weight Loss",
    excerptAr: "فهم الأسس العلمية لفقدان الوزن بشكل صحي.",
    excerptEn: "Understanding the scientific foundations of healthy weight loss.",
    contentAr: `<h2>العلم يشرح</h2><p>فقدان الوزن ليس مجرد معادلة سعرات حرارية.</p>`,
    contentEn: `<h2>Science Explains</h2><p>Weight loss isn't just a calorie equation.</p>`,
    category: "weight-management",
    tags: ["weight loss science", "metabolism"],
    keywords: "weight loss science, metabolism",
    metaTitleAr: "علم إنقاص الوزن",
    metaTitleEn: "Science of Weight Loss",
    pillarId: "weight-management",
    clusterId: "weight-management",
    targetKeyword: "weight loss science",
    wordCount: 1500,
    readTimeMinutes: 7
  },
  {
    slug: "lose-belly-fat-without-starving",
    titleAr: "كيف تفقد دهون البطن دون تجويع نفسك",
    titleEn: "How to Lose Belly Fat Without Starving Yourself",
    excerptAr: "استراتيجية ذكية لتوديع دهون البطن العنيدة.",
    excerptEn: "Smart strategy to bid farewell to stubborn belly fat.",
    contentAr: `<h2>الاعتقاد الخاطئ</h2><p>التجويع لا يحرق الدهون، بل يحرق العضلات.</p>`,
    contentEn: `<h2>The Misconception</h2><p>Starvation doesn't burn fat, it burns muscle.</p>`,
    category: "weight-management",
    tags: ["belly fat", "weight loss tips"],
    keywords: "belly fat, weight loss tips",
    metaTitleAr: "التخلص من دهون البطن",
    metaTitleEn: "Lose Belly Fat",
    pillarId: "weight-management",
    clusterId: "weight-management",
    targetKeyword: "lose belly fat",
    wordCount: 1300,
    readTimeMinutes: 6
  },
  {
    slug: "calories-versus-hormones-weight-loss",
    titleAr: "فهم السعرات الحرارية مقابل الهرمونات",
    titleEn: "Understanding Calories vs. Hormones in Weight Loss",
    excerptAr: "لماذا الهرمونات أهم من مجرد حساب السعرات.",
    excerptEn: "Why hormones matter more than just counting calories.",
    contentAr: `<h2>ما وراء السعرات الحرارية</h2><p>حساب السعرات وحده لا يكفي.</p>`,
    contentEn: `<h2>Beyond Calories</h2><p>Counting calories alone isn't enough.</p>`,
    category: "weight-management",
    tags: ["calories", "hormones"],
    keywords: "calories, hormones, weight loss",
    metaTitleAr: "السعرات مقابل الهرمونات",
    metaTitleEn: "Calories vs Hormones",
    pillarId: "weight-management",
    clusterId: "weight-management",
    targetKeyword: "calories hormones weight loss",
    wordCount: 1400,
    readTimeMinutes: 7
  },
  {
    slug: "best-time-eat-weight-loss",
    titleAr: "أفضل وقت للأكل من أجل إنقاص الوزن",
    titleEn: "The Best Time to Eat for Weight Loss",
    excerptAr: "توقيت الوجبات قد يكون أكثر أهمية من المحتوى.",
    excerptEn: "Meal timing may be more important than content.",
    contentAr: `<h2>ساعة الجسم الداخلية</h2><p>جيناتك تفضل أوقاتاً معينة للأكل.</p>`,
    contentEn: `<h2>Body's Internal Clock</h2><p>Your genes prefer certain times to eat.</p>`,
    category: "weight-management",
    tags: ["meal timing", "eating schedule"],
    keywords: "meal timing, eating schedule",
    metaTitleAr: "توقيت الأكل للرجيم",
    metaTitleEn: "Best Time to Eat for Weight Loss",
    pillarId: "weight-management",
    clusterId: "weight-management",
    targetKeyword: "best time to eat",
    wordCount: 1200,
    readTimeMinutes: 6
  },
  {
    slug: "break-weight-loss-plateaus",
    titleAr: "كيف تتجاوز مرحلة ثبات الوزن",
    titleEn: "How to Break Through Weight Loss Plateaus",
    excerptAr: "استراتيجيات فعالة للخروج من مرحلة الجمود.",
    excerptEn: "Effective strategies to get out of the plateau phase.",
    contentAr: `<h2>لماذا يحدث الثبات؟</h2><p>جسمك يتكيف مع تغيراتك.</p>`,
    contentEn: `<h2>Why Does It Happen?</h2><p>Your body adapts to your changes.</p>`,
    category: "weight-management",
    tags: ["weight loss plateau"],
    keywords: "weight loss plateau",
    metaTitleAr: "تجاوز ثبات الوزن",
    metaTitleEn: "Break Through Weight Loss Plateaus",
    pillarId: "weight-management",
    clusterId: "weight-management",
    targetKeyword: "weight loss plateau",
    wordCount: 1300,
    readTimeMinutes: 6
  },
  {
    slug: "metabolic-adaptation-overcome",
    titleAr: "فهم التكيف الأيضي وكيفية التغلب عليه",
    titleEn: "Understanding Metabolic Adaptation and How to Overcome It",
    excerptAr: "لماذا يتباطأ وزنك رغم الاستمرار في الحمية.",
    excerptEn: "Why your weight slows despite continuing the diet.",
    contentAr: `<h2>التكيف الأيضي</h2><p>جسمك ذكي. عندما تفقد الوزن، يستهلك سعرات أقل.</p>`,
    contentEn: `<h2>Metabolic Adaptation</h2><p>Your body is smart. When you lose weight, it burns fewer calories.</p>`,
    category: "weight-management",
    tags: ["metabolic adaptation", "metabolism"],
    keywords: "metabolic adaptation, metabolism",
    metaTitleAr: "التكيف الأيضي",
    metaTitleEn: "Metabolic Adaptation",
    pillarId: "weight-management",
    clusterId: "weight-management",
    targetKeyword: "metabolic adaptation",
    wordCount: 1400,
    readTimeMinutes: 7
  },
  {
    slug: "protein-weight-loss-muscle-preservation",
    titleAr: "دور البروتين في إنقاص الوزن والحفاظ على العضلات",
    titleEn: "The Role of Protein in Weight Loss and Muscle Preservation",
    excerptAr: "البروتين هو حليفك الأول في رحلة التنشيف.",
    excerptEn: "Protein is your number one ally in the cutting journey.",
    contentAr: `<h2>قوة البروتين</h2><p>البروتين يبقيك شبعاناً ويحمي عضلاتك.</p>`,
    contentEn: `<h2>The Power of Protein</h2><p>Protein keeps you full, protects your muscles.</p>`,
    category: "weight-management",
    tags: ["protein diet", "muscle preservation"],
    keywords: "protein diet, muscle preservation",
    metaTitleAr: "البروتين وإنقاص الوزن",
    metaTitleEn: "Protein for Weight Loss",
    pillarId: "weight-management",
    clusterId: "weight-management",
    targetKeyword: "protein weight loss",
    wordCount: 1200,
    readTimeMinutes: 6
  },
  {
    slug: "realistic-weight-loss-goals",
    titleAr: "كيف تحدد أهدافاً واقعية لإنقاص الوزن",
    titleEn: "How to Set Realistic Weight Loss Goals",
    excerptAr: "أهداف واقعية ومحددة وقابلة للقياس.",
    excerptEn: "Realistic, specific, measurable goals ensure success.",
    contentAr: `<h2>قاعدة SMART</h2><p>أهداف واقعية ومحددة وقابلة للقياس تضمن النجاح.</p>`,
    contentEn: `<h2>SMART Rule</h2><p>Realistic, specific, measurable goals ensure success.</p>`,
    category: "weight-management",
    tags: ["weight loss goals", "SMART goals"],
    keywords: "weight loss goals, SMART goals",
    metaTitleAr: "أهداف إنقاص الوزن",
    metaTitleEn: "Realistic Weight Loss Goals",
    pillarId: "weight-management",
    clusterId: "weight-management",
    targetKeyword: "weight loss goals",
    wordCount: 1100,
    readTimeMinutes: 5
  },
  // GUT HEALTH (8)
  {
    slug: "gut-health-foundations-wellness",
    titleAr: "أساسيات صحة الأمعاء للعافية الشاملة",
    titleEn: "Gut Health Foundations for Overall Wellness",
    excerptAr: "الأمعاء هي مركز صحتك الثاني.",
    excerptEn: "The gut is your second center of health.",
    contentAr: `<h2>ما هي صحة الأمعاء؟</h2><p>صحة الأمعاء تؤثر على كل شيء من الهضم إلى المناعة.</p>`,
    contentEn: `<h2>What is Gut Health?</h2><p>Gut health affects everything from digestion to immunity.</p>`,
    category: "gut-health",
    tags: ["gut health", "digestion", "probiotics"],
    keywords: "gut health, digestion, probiotics",
    metaTitleAr: "صحة الأمعاء",
    metaTitleEn: "Gut Health Foundations",
    pillarId: "gut-health",
    clusterId: "gut-health",
    targetKeyword: "gut health",
    wordCount: 1400,
    readTimeMinutes: 7
  },
  {
    slug: "microbiome-gut-brain-connection",
    titleAr: "الميكروبيوم: حلقة الوصل بين الأمعاء والدماغ",
    titleEn: "The Microbiome: Gut-Brain Connection",
    excerptAr: "اكتشف كيف تتواصل بكتيريا الأمعاء مع دماغك.",
    excerptEn: "Discover how gut bacteria communicate with your brain.",
    contentAr: `<h2>محور الأمعاء والدماغ</h2><p>الأمعاء تنتج 90% من السيروتونين في الجسم.</p>`,
    contentEn: `<h2>Gut-Brain Axis</h2><p>The gut produces 90% of the body's serotonin.</p>`,
    category: "gut-health",
    tags: ["microbiome", "gut-brain axis"],
    keywords: "microbiome, gut-brain axis",
    metaTitleAr: "الميكروبيوم والأمعاء",
    metaTitleEn: "Microbiome Gut-Brain Connection",
    pillarId: "gut-health",
    clusterId: "gut-health",
    targetKeyword: "gut brain connection",
    wordCount: 1300,
    readTimeMinutes: 6
  },
  {
    slug: "leaky-gut-syndrome-symptoms",
    titleAr: "متلازمة الأمعاء المتسربة: الأعراض والعلاج",
    titleEn: "Leaky Gut Syndrome: Symptoms and Treatment",
    excerptAr: "متى تصبح جدران الأمعاء مشكلة صحية.",
    excerptEn: "When gut walls become a health problem.",
    contentAr: `<h2>ما هي الأمعاء المتسربة؟</h2><p>المتلازمة تحدث عندما تتلف junctions خلايا الأمعاء.</p>`,
    contentEn: `<h2>What is Leaky Gut?</h2><p>The syndrome occurs when gut cell junctions are damaged.</p>`,
    category: "gut-health",
    tags: ["leaky gut", "gut syndrome"],
    keywords: "leaky gut, gut syndrome",
    metaTitleAr: "الأمعاء المتسربة",
    metaTitleEn: "Leaky Gut Syndrome",
    pillarId: "gut-health",
    clusterId: "gut-health",
    targetKeyword: "leaky gut syndrome",
    wordCount: 1400,
    readTimeMinutes: 7
  },
  {
    slug: "probiotics-benefits-gut-health",
    titleAr: "فوائد البروبيوتيك لصحة الأمعاء",
    titleEn: "Probiotics Benefits for Gut Health",
    excerptAr: "البكتيريا النافعة صديقك الأول.",
    excerptEn: "Beneficial bacteria are your number one friend.",
    contentAr: `<h2>ما هي البروبيوتيك؟</h2><p>البروبيوتيك هي بكتيريا نافعة تدعم صحة الأمعاء.</p>`,
    contentEn: `<h2>What are Probiotics?</h2><p>Probiotics are beneficial bacteria that support gut health.</p>`,
    category: "gut-health",
    tags: ["probiotics", "beneficial bacteria"],
    keywords: "probiotics, beneficial bacteria",
    metaTitleAr: "البروبيوتيك",
    metaTitleEn: "Probiotics Benefits",
    pillarId: "gut-health",
    clusterId: "gut-health",
    targetKeyword: "probiotics benefits",
    wordCount: 1200,
    readTimeMinutes: 6
  },
  {
    slug: "prebiotics-foods-gut-health",
    titleAr: "الأطعمة الغنية بالبريبيوتيك لصحة الأمعاء",
    titleEn: "Prebiotic Foods for Gut Health",
    excerptAr: "طعام البكتيريا النافعة.",
    excerptEn: "Food for beneficial bacteria.",
    contentAr: `<h2>قائمة البريبيوتيك</h2><p>البصل والثوم والموز والهندباء.</p>`,
    contentEn: `<h2>Prebiotic List</h2><p>Onions, garlic, bananas, and dandelion greens.</p>`,
    category: "gut-health",
    tags: ["prebiotics", "prebiotic foods"],
    keywords: "prebiotics, prebiotic foods",
    metaTitleAr: "الأطعمة البريبيوتيكية",
    metaTitleEn: "Prebiotic Foods",
    pillarId: "gut-health",
    clusterId: "gut-health",
    targetKeyword: "prebiotic foods",
    wordCount: 1100,
    readTimeMinutes: 5
  },
  {
    slug: "ibs-natural-management",
    titleAr: "إدارة القولون العصبي بشكل طبيعي",
    titleEn: "Natural Management of IBS",
    excerptAr: "استراتيجيات تخفف أعراض القولون العصبي.",
    excerptEn: "Strategies to relieve IBS symptoms.",
    contentAr: `<h2>ما هو القولون العصبي؟</h2><p>اضطراب وظيفي في الجهاز الهضمي.</p>`,
    contentEn: `<h2>What is IBS?</h2><p>A functional disorder of the digestive system.</p>`,
    category: "gut-health",
    tags: ["IBS", "irritable bowel"],
    keywords: "IBS, irritable bowel",
    metaTitleAr: "القولون العصبي",
    metaTitleEn: "IBS Management",
    pillarId: "gut-health",
    clusterId: "gut-health",
    targetKeyword: "IBS symptoms",
    wordCount: 1300,
    readTimeMinutes: 6
  },
  {
    slug: "fiber-gut-health-importance",
    titleAr: "أهمية الألياف لصحة الأمعاء",
    titleEn: "The Importance of Fiber for Gut Health",
    excerptAr: "لماذا تحتاج المزيد من الألياف.",
    excerptEn: "Why you need more fiber.",
    contentAr: `<h2>أنواع الألياف</h2><p>الألياف القابلة للذوبان وغير القابلة للذوبان.</p>`,
    contentEn: `<h2>Types of Fiber</h2><p>Soluble and insoluble fiber.</p>`,
    category: "gut-health",
    tags: ["fiber", "digestive health"],
    keywords: "fiber, digestive health",
    metaTitleAr: "الألياف الغذائية",
    metaTitleEn: "Fiber for Gut Health",
    pillarId: "gut-health",
    clusterId: "gut-health",
    targetKeyword: "fiber gut health",
    wordCount: 1200,
    readTimeMinutes: 6
  },
  {
    slug: "gut-inflammation-signs",
    titleAr: "علامات التهاب الأمعاء وكيفية علاجه",
    titleEn: "Signs of Gut Inflammation and How to Treat It",
    excerptAr: "اكتشف علامات الالتهاب المعوي.",
    excerptEn: "Discover signs of intestinal inflammation.",
    contentAr: `<h2>علامات الالتهاب</h2><p>الانتفاخ والألم والتغيرات في الهضم.</p>`,
    contentEn: `<h2>Signs of Inflammation</h2><p>Bloating, pain, and changes in digestion.</p>`,
    category: "gut-health",
    tags: ["gut inflammation", "treatment"],
    keywords: "gut inflammation, treatment",
    metaTitleAr: "التهاب الأمعاء",
    metaTitleEn: "Gut Inflammation Signs",
    pillarId: "gut-health",
    clusterId: "gut-health",
    targetKeyword: "gut inflammation",
    wordCount: 1400,
    readTimeMinutes: 7
  },
  // BEHAVIORAL NUTRITION (5)
  {
    slug: "emotional-eating-awareness",
    titleAr: "الوعي بالeating العاطفي",
    titleEn: "Emotional Eating Awareness",
    excerptAr: "متى يصبح الأكل رد فعل عاطفي.",
    excerptEn: "When eating becomes an emotional reaction.",
    contentAr: `<h2>ما هو الأكل العاطفي؟</h2><p>الأكل استجابة لمشاعر وليس للجوع.</p>`,
    contentEn: `<h2>What is Emotional Eating?</h2><p>Eating in response to emotions, not hunger.</p>`,
    category: "behavioral-nutrition",
    tags: ["emotional eating", "eating habits"],
    keywords: "emotional eating, eating habits",
    metaTitleAr: "الأكل العاطفي",
    metaTitleEn: "Emotional Eating Awareness",
    pillarId: "behavioral-nutrition",
    clusterId: "behavioral-nutrition",
    targetKeyword: "emotional eating",
    wordCount: 1300,
    readTimeMinutes: 6
  },
  {
    slug: "mindful-eating-practices",
    titleAr: "ممارسات الأكل الواعي",
    titleEn: "Mindful Eating Practices",
    excerptAr: "تذوق كل قضمة بوعي.",
    excerptEn: "Savor every bite mindfully.",
    contentAr: `<h2>أساسيات الأكل الواعي</h2><p>الانتباه الكامل لتجربة الأكل.</p>`,
    contentEn: `<h2>Mindful Eating Basics</h2><p>Full attention to the eating experience.</p>`,
    category: "behavioral-nutrition",
    tags: ["mindful eating", "awareness"],
    keywords: "mindful eating, awareness",
    metaTitleAr: "الأكل الواعي",
    metaTitleEn: "Mindful Eating Practices",
    pillarId: "behavioral-nutrition",
    clusterId: "behavioral-nutrition",
    targetKeyword: "mindful eating",
    wordCount: 1200,
    readTimeMinutes: 6
  },
  {
    slug: "food-cravings-science",
    titleAr: "علم الرغبة الشديدة في الطعام",
    titleEn: "The Science of Food Cravings",
    excerptAr: "لماذا تشتهي أطعمة معينة.",
    excerptEn: "Why you crave certain foods.",
    contentAr: `<h2>أسباب الرغبة</h2><p>الرغبة تنبعث من的大脑 ومن البكتيريا.</p>`,
    contentEn: `<h2>Causes of Cravings</h2><p>Cravings originate from the brain and bacteria.</p>`,
    category: "behavioral-nutrition",
    tags: ["food cravings", "hunger"],
    keywords: "food cravings, hunger",
    metaTitleAr: "الرغبة في الطعام",
    metaTitleEn: "Food Cravings Science",
    pillarId: "behavioral-nutrition",
    clusterId: "behavioral-nutrition",
    targetKeyword: "food cravings",
    wordCount: 1400,
    readTimeMinutes: 7
  },
  {
    slug: "stress-eating-solutions",
    titleAr: "حلول للأكل الناتج عن التوتر",
    titleEn: "Solutions for Stress Eating",
    excerptAr: "تحويل التوتر إلى عادات صحية.",
    excerptEn: "Transforming stress into healthy habits.",
    contentAr: `<h2>لماذا نأكل عند التوتر؟</h2><p>الكورتيزول يحفز الرغبة في الطعام.</p>`,
    contentEn: `<h2>Why Do We Eat When Stressed?</h2><p>Cortisol stimulates food cravings.</p>`,
    category: "behavioral-nutrition",
    tags: ["stress eating", "cortisol"],
    keywords: "stress eating, cortisol",
    metaTitleAr: "الأكل والتوتر",
    metaTitleEn: "Stress Eating Solutions",
    pillarId: "behavioral-nutrition",
    clusterId: "behavioral-nutrition",
    targetKeyword: "stress eating",
    wordCount: 1300,
    readTimeMinutes: 6
  },
  {
    slug: "habit-stacking-nutrition",
    titleAr: "تكديس العادات الغذائية الناجحة",
    titleEn: "Habit Stacking for Nutrition Success",
    excerptAr: "اربط عادات جديدة ب-existing ones.",
    excerptEn: "Link new habits to existing ones.",
    contentAr: `<h2>كيف يعمل تكديس العادات</h2><p>ربط سلوك جديد بسلوك قائم.</p>`,
    contentEn: `<h2>How Habit Stacking Works</h2><p>Linking a new behavior to an existing one.</p>`,
    category: "behavioral-nutrition",
    tags: ["habit stacking", "nutrition habits"],
    keywords: "habit stacking, nutrition habits",
    metaTitleAr: "تكديس العادات",
    metaTitleEn: "Habit Stacking Nutrition",
    pillarId: "behavioral-nutrition",
    clusterId: "behavioral-nutrition",
    targetKeyword: "habit stacking nutrition",
    wordCount: 1200,
    readTimeMinutes: 6
  },
  // HORMONAL BALANCE (6)
  {
    slug: "hormones-metabolism-connection",
    titleAr: "العلاقة بين الهرمونات والتمثيل الغذائي",
    titleEn: "The Connection Between Hormones and Metabolism",
    excerptAr: "كيف تحكم الهرمونات في وزنك وطاقتك.",
    excerptEn: "How hormones control your weight and energy.",
    contentAr: `<h2>الهرمونات الرئيسية</h2><p>الأنسولين واللبتين والجرلين.</p>`,
    contentEn: `<h2>Key Hormones</h2><p>Insulin, leptin, and ghrelin.</p>`,
    category: "hormonal-balance",
    tags: ["hormones", "metabolism"],
    keywords: "hormones, metabolism",
    metaTitleAr: "الهرمونات والاستقلاب",
    metaTitleEn: "Hormones and Metabolism",
    pillarId: "hormonal-balance",
    clusterId: "hormonal-balance",
    targetKeyword: "hormones metabolism",
    wordCount: 1400,
    readTimeMinutes: 7
  },
  {
    slug: "thyroid-weight-connection",
    titleAr: "العلاقة بين الغدة الدرقية والوزن",
    titleEn: "The Thyroid-Weight Connection",
    excerptAr: "كيف تؤثر الغدة الدرقية على التمثيل الغذائي.",
    excerptEn: "How the thyroid affects metabolism.",
    contentAr: `<h2>وظيفة الغدة الدرقية</h2><p>الغدة الدرقية تنظم سرعة الاستقلاب.</p>`,
    contentEn: `<h2>Thyroid Function</h2><p>The thyroid regulates metabolic rate.</p>`,
    category: "hormonal-balance",
    tags: ["thyroid", "hypothyroidism"],
    keywords: "thyroid, hypothyroidism",
    metaTitleAr: "الغدة الدرقية والوزن",
    metaTitleEn: "Thyroid Weight Connection",
    pillarId: "hormonal-balance",
    clusterId: "hormonal-balance",
    targetKeyword: "thyroid weight",
    wordCount: 1500,
    readTimeMinutes: 7
  },
  {
    slug: "cortisol-management-stress",
    titleAr: "إدارة الكورتيزول والتوتر",
    titleEn: "Managing Cortisol and Stress",
    excerptAr: "تحكم في هرمون التوتر.",
    excerptEn: "Control the stress hormone.",
    contentAr: `<h2>ما هو الكورتيزول؟</h2><p>هرمون التوتر الذي يؤثر على الوزن.</p>`,
    contentEn: `<h2>What is Cortisol?</h2><p>The stress hormone that affects weight.</p>`,
    category: "hormonal-balance",
    tags: ["cortisol", "stress management"],
    keywords: "cortisol, stress management",
    metaTitleAr: "إدارة الكورتيزول",
    metaTitleEn: "Cortisol Management",
    pillarId: "hormonal-balance",
    clusterId: "hormonal-balance",
    targetKeyword: "cortisol management",
    wordCount: 1300,
    readTimeMinutes: 6
  },
  {
    slug: "estrogen-balance-women",
    titleAr: "التوازن الاستروجيني عند النساء",
    titleEn: "Estrogen Balance in Women",
    excerptAr: "أهمية التوازن الهرموني النسائي.",
    excerptEn: "The importance of female hormonal balance.",
    contentAr: `<h2>دور الاستروجين</h2><p>الاستروجين يؤثر على كل شيء من المزاج إلى التمثيل الغذائي.</p>`,
    contentEn: `<h2>Role of Estrogen</h2><p>Estrogen affects everything from mood to metabolism.</p>`,
    category: "hormonal-balance",
    tags: ["estrogen", "women health"],
    keywords: "estrogen, women health",
    metaTitleAr: "التوازن الاستروجيني",
    metaTitleEn: "Estrogen Balance Women",
    pillarId: "hormonal-balance",
    clusterId: "hormonal-balance",
    targetKeyword: "estrogen balance",
    wordCount: 1400,
    readTimeMinutes: 7
  },
  {
    slug: "testosterone-men-metabolism",
    titleAr: "التستوستيرون والتمثيل الغذائي عند الرجال",
    titleEn: "Testosterone and Metabolism in Men",
    excerptAr: "دور التستوستيرون في صحة الرجل.",
    excerptEn: "The role of testosterone in men's health.",
    contentAr: `<h2>وظيفة التستوستيرون</h2><p>التستوستيرون ينظم كتلة العضلات والدهون.</p>`,
    contentEn: `<h2>Testosterone Function</h2><p>Testosterone regulates muscle mass and fat.</p>`,
    category: "hormonal-balance",
    tags: ["testosterone", "men health"],
    keywords: "testosterone, men health",
    metaTitleAr: "التستوستيرون والرجال",
    metaTitleEn: "Testosterone Men Metabolism",
    pillarId: "hormonal-balance",
    clusterId: "hormonal-balance",
    targetKeyword: "testosterone metabolism",
    wordCount: 1300,
    readTimeMinutes: 6
  },
  {
    slug: "hormone-healing-foods",
    titleAr: "أطعمة تعزز التوازن الهرموني",
    titleEn: "Foods That Support Hormonal Balance",
    excerptAr: "قائمة الأطعمة الهرمونية.",
    excerptEn: "The hormonal food list.",
    contentAr: `<h2>أطعمة متوازنة</h2><p>الدهون الصحية والبروتين والألياف.</p>`,
    contentEn: `<h2>Balancing Foods</h2><p>Healthy fats, protein, and fiber.</p>`,
    category: "hormonal-balance",
    tags: ["hormone foods", "balanced diet"],
    keywords: "hormone foods, balanced diet",
    metaTitleAr: "أطعمة التوازن الهرموني",
    metaTitleEn: "Hormone Healing Foods",
    pillarId: "hormonal-balance",
    clusterId: "hormonal-balance",
    targetKeyword: "hormone balancing foods",
    wordCount: 1200,
    readTimeMinutes: 6
  },
  // MENTAL WELLNESS (6)
  {
    slug: "brain-gut-connection",
    titleAr: "العلاقة بين الدماغ والأمعاء",
    titleEn: "The Brain-Gut Connection",
    excerptAr: "كيف يؤثر الجهاز الهضمي على صحتك النفسية.",
    excerptEn: "How the digestive system affects your mental health.",
    contentAr: `<h2>محور الدماغ والأمعاء</h2><p>الأمعاء ترسل إشارات إلى الدماغ.</p>`,
    contentEn: `<h2>The Gut-Brain Axis</h2><p>The gut sends signals to the brain.</p>`,
    category: "mental-wellness",
    tags: ["brain gut", "mental health"],
    keywords: "brain gut, mental health",
    metaTitleAr: "الدماغ والأمعاء",
    metaTitleEn: "Brain Gut Connection",
    pillarId: "mental-wellness",
    clusterId: "mental-wellness",
    targetKeyword: "brain gut connection",
    wordCount: 1300,
    readTimeMinutes: 6
  },
  {
    slug: "sleep-mental-health-impact",
    titleAr: "تأثير النوم على الصحة النفسية",
    titleEn: "Sleep's Impact on Mental Health",
    excerptAr: "النوم الجيد يبدأ من هنا.",
    excerptEn: "Good sleep starts here.",
    contentAr: `<h2>لماذا النوم مهم؟</h2><p>النوم يعيد ضبط الدماغ والهرمونات.</p>`,
    contentEn: `<h2>Why Sleep Matters?</h2><p>Sleep resets the brain and hormones.</p>`,
    category: "mental-wellness",
    tags: ["sleep", "mental health"],
    keywords: "sleep, mental health",
    metaTitleAr: "النوم والصحة النفسية",
    metaTitleEn: "Sleep Mental Health Impact",
    pillarId: "mental-wellness",
    clusterId: "mental-wellness",
    targetKeyword: "sleep mental health",
    wordCount: 1400,
    readTimeMinutes: 7
  },
  {
    slug: "anxiety-nutrition-connection",
    titleAr: "العلاقة بين القلق والتغذية",
    titleEn: "The Anxiety-Nutrition Connection",
    excerptAr: "كيف يمكن للطعام أن يساعد في تهدئة القلق.",
    excerptEn: "How food can help calm anxiety.",
    contentAr: `<h2>المغذيات المضادة للقلق</h2><p>المغنيسيوم وأوميغا 3 وفيتامين B.</p>`,
    contentEn: `<h2>Anti-Anxiety Nutrients</h2><p>Magnesium, omega-3, and vitamin B.</p>`,
    category: "mental-wellness",
    tags: ["anxiety", "nutrition"],
    keywords: "anxiety, nutrition",
    metaTitleAr: "القلق والتغذية",
    metaTitleEn: "Anxiety Nutrition Connection",
    pillarId: "mental-wellness",
    clusterId: "mental-wellness",
    targetKeyword: "anxiety nutrition",
    wordCount: 1300,
    readTimeMinutes: 6
  },
  {
    slug: "depression-diet-relationship",
    titleAr: "العلاقة بين الاكتئاب والنظام الغذائي",
    titleEn: "The Depression-Diet Relationship",
    excerptAr: "الاكتئاب يبدا في طبقك.",
    excerptEn: "Depression starts in your plate.",
    contentAr: `<h2>النظام الغذائي المضاد للاكتئاب</h2><p>الأطعمة الغنية بالمغذيات تحسن المزاج.</p>`,
    contentEn: `<h2>Anti-Depression Diet</h2><p>Nutrient-rich foods improve mood.</p>`,
    category: "mental-wellness",
    tags: ["depression", "diet"],
    keywords: "depression, diet",
    metaTitleAr: "الاكتئاب والنظام الغذائي",
    metaTitleEn: "Depression Diet Relationship",
    pillarId: "mental-wellness",
    clusterId: "mental-wellness",
    targetKeyword: "depression diet",
    wordCount: 1400,
    readTimeMinutes: 7
  },
  {
    slug: "focus-foods-brain-performance",
    titleAr: "أطعمة تعزز التركيز وأداء الدماغ",
    titleEn: "Foods That Boost Focus and Brain Performance",
    excerptAr: "وقود الدماغ الأمثل.",
    excerptEn: "Optimal brain fuel.",
    contentAr: `<h2>أطعمة الدماغ</h2><p>التوت الأزرق والأفوكادو والمكسرات.</p>`,
    contentEn: `<h2>Brain Foods</h2><p>Blueberries, avocados, and nuts.</p>`,
    category: "mental-wellness",
    tags: ["brain foods", "focus"],
    keywords: "brain foods, focus",
    metaTitleAr: "أطعمة التركيز",
    metaTitleEn: "Focus Foods Brain Performance",
    pillarId: "mental-wellness",
    clusterId: "mental-wellness",
    targetKeyword: "brain foods focus",
    wordCount: 1200,
    readTimeMinutes: 6
  },
  {
    slug: "stress-foods-avoid",
    titleAr: "أطعمة يجب تجنبها عند التوتر",
    titleEn: "Foods to Avoid When Stressed",
    excerptAr: "المشروبات المحفزة للتوتر.",
    excerptEn: "Drinks that fuel stress.",
    contentAr: `<h2>أطعمة تزيد التوتر</h2><p>السكريات المكررة والكافيين الزائد.</p>`,
    contentEn: `<h2>Stress-Fueling Foods</h2><p>Refined sugars and excess caffeine.</p>`,
    category: "mental-wellness",
    tags: ["stress foods", "avoid"],
    keywords: "stress foods, avoid",
    metaTitleAr: "أطعمة التوتر",
    metaTitleEn: "Stress Foods to Avoid",
    pillarId: "mental-wellness",
    clusterId: "mental-wellness",
    targetKeyword: "foods to avoid stress",
    wordCount: 1100,
    readTimeMinutes: 5
  },
  // LIFESTYLE MEDICINE (5)
  {
    slug: "circadian-rhythm-health",
    titleAr: "الإيقاع اليومي وأثره على الصحة",
    titleEn: "Circadian Rhythm and Its Impact on Health",
    excerptAr: "تناغم مع ساعة جسمك البيولوجية.",
    excerptEn: "In harmony with your biological clock.",
    contentAr: `<h2>ما هو الإيقاع اليومي؟</h2><p>الساعة البيولوجية تتحكم في كل شيء.</p>`,
    contentEn: `<h2>What is Circadian Rhythm?</h2><p>The biological clock controls everything.</p>`,
    category: "lifestyle-medicine",
    tags: ["circadian rhythm", "sleep cycle"],
    keywords: "circadian rhythm, sleep cycle",
    metaTitleAr: "الإيقاع اليومي",
    metaTitleEn: "Circadian Rhythm Health",
    pillarId: "lifestyle-medicine",
    clusterId: "lifestyle-medicine",
    targetKeyword: "circadian rhythm health",
    wordCount: 1300,
    readTimeMinutes: 6
  },
  {
    slug: "morning-routine-metabolism",
    titleAr: "روتين الصباح لتحفيز الاستقلاب",
    titleEn: "Morning Routine to Boost Metabolism",
    excerptAr: "ابدأ يومك بشكل صحيح.",
    excerptEn: "Start your day right.",
    contentAr: `<h2>عادات الصباح</h2><p>الضوء والشمس والماء.</p>`,
    contentEn: `<h2>Morning Habits</h2><p>Light, sun, and water.</p>`,
    category: "lifestyle-medicine",
    tags: ["morning routine", "metabolism"],
    keywords: "morning routine, metabolism",
    metaTitleAr: "روتين الصباح",
    metaTitleEn: "Morning Routine Metabolism",
    pillarId: "lifestyle-medicine",
    clusterId: "lifestyle-medicine",
    targetKeyword: "morning routine metabolism",
    wordCount: 1200,
    readTimeMinutes: 6
  },
  {
    slug: "exercise-timing-optimal-results",
    titleAr: "توقيت التمارين للحصول على أفضل النتائج",
    titleEn: "Exercise Timing for Optimal Results",
    excerptAr: "متى تمارس الرياضة لأفضل فعالية.",
    excerptEn: "When to exercise for best effectiveness.",
    contentAr: `<h2>أفضل وقت للرياضة</h2><p>الصباح أم المساء؟ العلم يجيب.</p>`,
    contentEn: `<h2>Best Time to Exercise</h2><p>Morning or evening? Science answers.</p>`,
    category: "lifestyle-medicine",
    tags: ["exercise timing", "workout"],
    keywords: "exercise timing, workout",
    metaTitleAr: "توقيت التمارين",
    metaTitleEn: "Exercise Timing Results",
    pillarId: "lifestyle-medicine",
    clusterId: "lifestyle-medicine",
    targetKeyword: "exercise timing",
    wordCount: 1400,
    readTimeMinutes: 7
  },
  {
    slug: "hydration-metabolism-boost",
    titleAr: "الترطيب وتأثيره على الاستقلاب",
    titleEn: "Hydration and Its Effect on Metabolism",
    excerptAr: "الماء هو أساس الحياة والاستقلاب.",
    excerptEn: "Water is the foundation of life and metabolism.",
    contentAr: `<h2>كم تحتاج من الماء؟</h2><p>الترطيب الأمثل يحرق السعرات.</p>`,
    contentEn: `<h2>How Much Water Do You Need?</h2><p>Optimal hydration burns calories.</p>`,
    category: "lifestyle-medicine",
    tags: ["hydration", "water metabolism"],
    keywords: "hydration, water metabolism",
    metaTitleAr: "الترطيب والاستقلاب",
    metaTitleEn: "Hydration Metabolism Boost",
    pillarId: "lifestyle-medicine",
    clusterId: "lifestyle-medicine",
    targetKeyword: "hydration metabolism",
    wordCount: 1100,
    readTimeMinutes: 5
  },
  {
    slug: "detoxification-natural-body-cleanse",
    titleAr: "التخلص من السموم: تنظيف الجسم طبيعياً",
    titleEn: "Detoxification: Natural Body Cleansing",
    excerptAr: "دعم أجهزة التنظيف الداخلية.",
    excerptEn: "Supporting internal cleansing systems.",
    contentAr: `<h2>أجهزة التنظيف الطبيعية</h2><p>الكبد والكلى والجلد.</p>`,
    contentEn: `<h2>Natural Cleansing Systems</h2><p>The liver, kidneys, and skin.</p>`,
    category: "lifestyle-medicine",
    tags: ["detox", "body cleanse"],
    keywords: "detox, body cleanse",
    metaTitleAr: "التخلص من السموم",
    metaTitleEn: "Natural Detoxification",
    pillarId: "lifestyle-medicine",
    clusterId: "lifestyle-medicine",
    targetKeyword: "natural detoxification",
    wordCount: 1300,
    readTimeMinutes: 6
  }
];

// ============================================================
// API HANDLER
// ============================================================
export async function seedAllContentHandler(req: Request, res: Response) {
  try {
    const startTime = Date.now();
    console.log("[SeedAllContent] Starting bulk content seeding...");

    // Check current counts
    const currentArticles = await getArticlesCount();
    const currentResearch = await getResearchCount();
    console.log(`[SeedAllContent] Current: ${currentArticles} articles, ${currentResearch} studies`);

    let articlesCreated = 0;
    let articlesSkipped = 0;

    // Create articles
    for (const article of ARTICLES) {
      try {
        await createBlogArticle({
          slug: article.slug,
          titleAr: article.titleAr,
          titleEn: article.titleEn,
          excerptAr: article.excerptAr,
          excerptEn: article.excerptEn,
          contentAr: article.contentAr,
          contentEn: article.contentEn,
          category: article.category,
          tags: article.tags,
          keywords: article.keywords,
          metaTitleAr: article.metaTitleAr || article.titleAr,
          metaTitleEn: article.metaTitleEn || article.titleEn,
          metaDescriptionAr: article.metaDescriptionAr || article.excerptAr,
          metaDescriptionEn: article.metaDescriptionEn || article.excerptEn,
          pillarId: article.pillarId,
          clusterId: article.clusterId,
          targetKeyword: article.targetKeyword,
          wordCount: article.wordCount,
          status: "published",
          language: "both",
          faqSchema: [],
          internalLinks: [],
          readTimeMinutes: article.readTimeMinutes,
          isPublished: true,
          publishedAt: new Date(),
        });
        articlesCreated++;
        console.log(`[SeedAllContent] ✅ Created article: ${article.slug}`);
      } catch (err: any) {
        if (err.message?.includes("Duplicate") || err.code === "ER_DUP_ENTRY") {
          articlesSkipped++;
          console.log(`[SeedAllContent] ⏭️  Skipped (exists): ${article.slug}`);
        } else {
          console.error(`[SeedAllContent] ❌ Error creating ${article.slug}:`, err.message);
        }
      }
    }

    const duration = Date.now() - startTime;

    // Get final counts
    const finalArticles = await getArticlesCount();
    const finalResearch = await getResearchCount();

    res.json({
      ok: true,
      summary: {
        duration: `${duration}ms`,
        articlesCreated,
        articlesSkipped,
        totalArticles: finalArticles,
        researchStudies: finalResearch
      },
      message: `✅ Successfully seeded ${articlesCreated} articles in ${duration}ms`
    });

    console.log(`[SeedAllContent] ✅ Complete: ${articlesCreated} created, ${articlesSkipped} skipped, ${finalArticles} total articles`);

  } catch (error: any) {
    console.error("[SeedAllContent] Error:", error);
    res.status(500).json({ error: error?.message || "Unknown error" });
  }
}
